import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import Link from 'next/link';
import Image from 'next/image';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Nutrition Facts Scanner App',
  description: 'Generated by Next.js, Barcode Detection API, and USDA and OpenFoodFacts APIs',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <nav className="flex items-center gap-2 w-full bg-background-200 p-2">
            <Link href="/app">
              <Image src="/nutrition-facts-scanner-logo.svg" alt="logo" width="50" height="50" />
            </Link>
            <h1 className="text-xl font-semibold">Nutrition Facts Scanner</h1>
          </nav>
          {children}
      </body>
    </html>
  )
}
